apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  template:
    spec:
      containers:
      - name: db
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: POSTGRES_DB
          value: "app_dev"
        - name: POSTGRES_USER
          value: "app_dev"
        - name: POSTGRES_PASSWORD
          value: "devpassword"  # Note: In real setup, use Kubernetes secrets
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 500Mi  # Smaller storage for dev 