apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - nginx-config.yaml

configMapGenerator:
  - name: app1-index
    files:
      - index.html

patches:
  - path: resource-patch.yaml

labels:
  - pairs:
      environment: prod 