apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: file:///apps
    targetRevision: HEAD
    path: app1/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 