apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Geniekort/k8s-envs-prototype.git
    targetRevision: main
    path: apps/db/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 