apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - nginx-config.yaml

configMapGenerator:
  - name: app2-index
    files:
      - index.html

patches:
  - path: resource-patch.yaml

# Add environment label only to metadata, not to selector
commonAnnotations:
  environment: prod

labels:
  - pairs:
      environment: prod 