apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base

patchesStrategicMerge:
- resource-patch.yaml

configMapGenerator:
- name: nginx-config
  behavior: create
  files:
  - nginx-config.yaml
- name: app-content
  behavior: create
  files:
  - index.html 